### ISSUE TITLE
UI update for buttons on starting page is needed

### ISSUE THREAD

**Issue by skajushka** [ahlinist/tempvs#22]
### Expected result 

Log in / Register button should be extremely obvious and well-marked.

**Comment by ahlinist** [comment]
Replaced glyphicon with text

**Comment by skajushka** [comment]
Verified on dev.
In addition it would be better to add same text button under the text.

**Comment by ahlinist** [comment]
Added a button to the text.

**Comment by skajushka** [comment]
Verified on dev.
That's better :)
