### ISSUE TITLE
"Profile Id" field has no obvious meaning and no hints for user (User Profile)

### ISSUE THREAD

**Issue by skajushka** [ahlinist/tempvs#24]
### Expected result

Every field, especially those which has no obvious meaning - like Profile Id, needs to have a hint nearby in order to help user get aware of the product without feeling uncomfortable. E.x., it could be implemented as "?" with tool-tip on hover.

![1](https://user-images.githubusercontent.com/6736904/36728614-6143d706-1bd2-11e8-9be2-2bfe789331a4.png)

**Comment by ahlinist** [comment]
To be resolved as a part of #28
