### ISSUE TITLE
Tooltip for Edit Avatar button doesn't disappear after user has stopped hovering the cursor over the button

### ISSUE THREAD

**Issue by skajushka** [ahlinist/tempvs#26]
### Expected result

Tooltip disappears after user has stopped hovering the cursor over the button

![2](https://user-images.githubusercontent.com/6736904/36791974-3ba546b4-1caa-11e8-9790-4b13f039229a.png)

**Comment by ahlinist** [comment]
Hid the tooltip when modal is opened.

**Comment by skajushka** [comment]
Verified on dev. 
Issue is mostly fixed :)
