### ISSUE TITLE
Edit avatar modal is cut in case if avatar modal is set to minimal width

### ISSUE THREAD

**Issue by skajushka** [ahlinist/tempvs#27]
### Expected result 

Edit avatar modal window hovers over the avatar modal window and doesn't depend on the width of avatar modal.

![1](https://user-images.githubusercontent.com/6736904/36890687-e5c00c54-1e0f-11e8-82ce-c0a4c36d2e43.png)

**Comment by ahlinist** [comment]
Fixed.

**Comment by skajushka** [comment]
Not sure if it's fixed correctly. 
For now "No file selected" is cut.
Please, the the screenshot attached.

![1](https://user-images.githubusercontent.com/6736904/36964502-eb8b7358-2067-11e8-94e9-3bc870e5f1cf.png)

**Comment by ahlinist** [comment]
Done.

**Comment by skajushka** [comment]
Verified.
Issue is fixed.
